### ISSUE TITLE
Uninitialized constant Poise

### ISSUE THREAD

**Issue by NickMRamirez** [rackspace-cookbooks/elkstack#149]
Currently getting the following error when using either chef-solo or chef-zero. Tested on versions 5.0.2, 5.0.1 and 5.0.0. Tested via https://github.com/NickMRamirez/ElkstackProject
```
===================================================================
Recipe Compile Error in /tmp/vagrant-chef/2cbca9b9807b669de89b4ee4a
dce145a/cookbooks/kibana_lwrp/libraries/install.rb
===================================================================

NameError
---------
uninitialized constant Chef::Resource::KibanaInstall::Poise
Cookbook Trace:
---------------
==> /tmp/vagrant-chef/2cbca9b9807b669de89b4ee4adce145a/cookbooks/kiba
na_lwrp/libraries/install.rb:12:in `<class:KibanaInstall>'
==> /tmp/vagrant-chef/2cbca9b9807b669de89b4ee4adce145a/cookbooks/kiba
na_lwrp/libraries/install.rb:11:in `<class:Chef>'
==> /tmp/vagrant-chef/2cbca9b9807b669de89b4ee4adce145a/cookbooks/kiba
na_lwrp/libraries/install.rb:10:in `<top (required)>'

Relevant File Content:
----------------------
/tmp/vagrant-chef/2cbca9b9807b669de89b4ee4adce145a/cookbooks/kibana
_lwrp/libraries/install.rb:
5:  # Author:: Paul Czarkowski
6:  # License:: Apache 2.0
7:  #
8:  # Copyright 2014, John E. Vincent
9:
10:  class Chef
11:    class Resource::KibanaInstall < Resource
12>>     include Poise
13:
14:      actions(:create, :remove)
15:
```

**Comment by martinb3** [comment]
I'm pretty sure this is a result of the upstream poise library releasing a 2.0 version. In any case, the actual issue is in another cookbook `kibana_lwrp`, so it would be better if we reported the issue there. I filed the issue in the actual cookbook that's throwing the error -- https://github.com/lusis/chef-kibana/issues/90.

In the mean time, a workaround would be to pin back poise yourself using a Berksfile entry.
